"""empty message

Revision ID: 2ed96bbe2fd7
Revises: f2246ab8c7d7
Create Date: 2021-11-27 14:15:06.231970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed96bbe2fd7'
down_revision = 'f2246ab8c7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password', sa.String(length=255), nullable=False))
  
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'password')
    # ### end Alembic commands ###
